### PR TITLE
Py3 compatibility fixes (Refs: #6)

### PR DESCRIPTION
**Pull request by akabos**
Fixes to make all tests pass on Python 3.3 and 3.4.

### CODE REVIEW

**Comment by pixelogik** [comment]
Thx mate! Did you check that this still works with Python 2.7.x?

**Comment by akabos** [comment]
Sure. All tests pass on 2.7, 3.3 and 3.4. I added `tox.ini` to easily run tests on multiple python versions. 

I can also try and set up TravisCI if you like.

**Comment by pixelogik** [comment]
Awesome. 

I will check TravisCI for now, because I wanted to use it anyway at some point. I will ping you if I need help.

**Comment by pixelogik** [comment]
@akabos Hm, there seem to be some issues when running the tests. 

For one I added mockredis, because that is needed. 

On the other hand past.builtins is not available in Python 2.7? Running the tests failed on my machine saying that. Removing the imports however resulted in multiple fails during the tests. 

If you wanna help with that and/or TravisCI, I would be glad.

**Comment by akabos** [comment]
@pixelogik Can't reproduce. How exactly you run tests?

**Comment by pixelogik** [comment]
python run_tests.py

**Comment by pixelogik** [comment]
I get ImportError: No module named past.builtins

**Comment by pixelogik** [comment]
(I do not have Python3 installed, just using 2.7)

**Comment by akabos** [comment]
That's very strange, because it works perfectly for me in newly created 2.7 venv. Let's ask Travis to run all that and se what he have to say.

**Comment by akabos** [comment]
https://gist.github.com/akabos/b40ba19e51113ae51fc7

**Comment by pixelogik** [comment]
Ok weird. Maybe my OSX setup is broken :)

**Comment by pixelogik** [comment]
@akabos Could you help with TravisCI?

**Comment by akabos** [comment]
Yup, doing that right now.

**Comment by pixelogik** [comment]
Awesome

**Comment by akabos** [comment]
I'll create new pull request once Travis config is working.

**Comment by akabos** [comment]
@pixelogik 

Having some difficulties running that on Travis (https://travis-ci.org/akabos/NearPy). Installing NumPy and SciPy from sources takes _very_ long time. I found some hints on installing them with conda, but it doesn't seem to work properly. I can't continue today, but I definitely don't give up. I'll keep you updated.

**Comment by pixelogik** [comment]
Ok. Thanks mate! Looking forward to it.

**Comment by akabos** [comment]
See pull request https://github.com/pixelogik/NearPy/pull/40

**Pull request merged**
